# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'FirebaseSDK Issues' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseSDK Issues
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher'
  pod 'RxDataSources'
  
end
